version: '3.8'

services:
  hadoop-master:
    image: yassern1/hadoop-spark-jupyter:1.0.3
    container_name: hadoop-master
    hostname: hadoop-master
    ports:
      - "9870:9870"  
      - "8088:8088"  
      - "7077:7077"  
      - "19888:19888" 
      - "8080:8080"  
      - "9000:9000" 
    volumes:
      - type: bind
        source: D:/DockerImages/hadoop_project
        target: /shared_volume
    networks:
      - hadoop-net

  hadoop-slave1:
    image: yassern1/hadoop-spark-jupyter:1.0.3
    container_name: hadoop-slave1
    hostname: hadoop-slave1
    ports:
      - "8040:8042"
    networks:
      - hadoop-net

  hadoop-slave2:
    image: yassern1/hadoop-spark-jupyter:1.0.3
    container_name: hadoop-slave2
    hostname: hadoop-slave2
    ports:
      - "8041:8042" 
    networks:
      - hadoop-net

networks:
  hadoop-net:
    driver: bridge